default: &default
  adapter: postgresql
  user:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bookstore_development

test: &test
  <<: *default
  database: bookstore_test

cucumber:
  <<: *test
  database: bookstore_cucumber
